config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'contacts#index'
  resources :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.all
  end

  def new
    @contact = Contact.new
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to contact_path(@contact), notice: "Your contact has been created !"
    else
      render :new
    end
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])
    @contact.update(contact_params)
    redirect_to contacts_path
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    redirect_to contacts_path
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :address, :country, :phone)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_form.html.erb
<%= simple_form_for(@contact) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :country %>
    <%= f.input :phone %>
    <%= f.button :submit, class: "btn btn-primary" %>
    <%= link_to "Cancel", contacts_path, class: "btn btn-primary" %>
<% end %>

app/views/contacts/edit.html.erb
<div class="container mt-4">
<h1>Edit Contact</h1>
  <div class="form-container">
    <%= render "form", contact: @contact %>
  </div>
</div>

app/views/contacts/index.html.erb
<div class="container">
    <div class="contact-head">
        <h1>All contacts</h1>
        <%= link_to "Create new contact", new_contact_path, class:"btn btn-contact"  %>
    </div>
    
    <% @contacts.each do |contact|%>

        <%= link_to contact_path(contact), class:"text-decoration-none" do %>

            <div class="contact-card-sm">
                <div class="contact-card-sm-content">
                <i class="fas fa-user-circle"></i>
                <p><%= contact.name%></p>
                </div>

                <div class="contact-card-sm-actions">

                    <%= link_to icon('fas', 'edit'), edit_contact_path(contact)  %>

                    <%= link_to icon('fas', 'trash'), 
                    contact_path(contact),
                    method: :delete,
                    data: { confirm: "Are you sure ?" } %>

                </div>
            </div>

        <% end %>

    <% end %>

</div>

app/views/contacts/new.html.erb
<div class="container">
  <div class="form-container">
    <%= render "form", contact: @contact %>
  </div>
</div>

app/views/contacts/show.html.erb
<div class="container">
  <div class="contact-card mt-4">
    <i class="far fa-address-book"></i>
    <div class="contact-card-info">
      <h4><%= @contact.name%></h4>
      <p><%= @contact.address%></p>
      <p><%= @contact.country%></p>
      <p><%= @contact.phone%></p>
    </div>
  </div>
  <%= link_to "Back", contacts_path, class: "btn btn-primary mt-2" %>
  <%= link_to "Edit", edit_contact_path(@contact), class: "btn btn-primary mt-2" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/chrisgeek07", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>